id: unitsarefailing_identify_file
hints:
- Look at the test results for a failed run
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Ok, great. Now that we've found the problem, can you find out which file contains the flaky tests?"
        delay: 1300
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "comments_test"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Yep, looks like that file contains all the flakes... Good job 👏👏"
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Umm, I'm not seeing any errors there. Maybe it's a different file?"
              delay: 1400
