id: unitsarefailing_identify_flakiness
learningObjectives: 
- What are flakey tests and how to identify them
hints:
- Try to run the tests multiple times and see if the results are consistent
- You can run the tests using `psuedo code to run test`
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hey. Navi told me they had a test suite that used to run against their actual DB 🙄. Carl was working on migrating it to in memory testing.."
        delay: 2000
      - text: "It was supposedly ready for production, but the tests are failing for me. Can you try running them?"
        delay: 3500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: keen
          messages:
          - text: "I remember Carl said it worked for him, but it didn't work for me. Not sure what's going on here"
            delay: 2000
      - actionId: finish_step
